let name="✯✯✯✯✯✯✯✯✎✎𝐑𝐄𝐏𝐎𝐑𝐓 𝐂𝐀𝐑𝐃✎✎✯✯✯✯✯✯✯✯✯✯";
console.log(name);
let p="==================================";
console.log(p);
let name1="𝗡𝗮𝗺𝗲      = Rohit Sharma.";
console.log(name1);
let name2="𝗦𝗰𝗵𝗼𝗼𝗹    = Saint Michael School.";
console.log(name2);
let name3="𝗚𝗿𝗮𝗱𝗲     = 10th";
console.log(name3);
let name4="𝗦𝗲𝗰𝘁𝗶𝗼𝗻   = C";
console.log(name4);
let name5="𝗥𝗢𝗟𝗟 𝗻𝗼   = 𝟱𝟮";
console.log(name5);
 let x="==================================";
console.log(x);
let marksScored="* MⷨAͣRͬᴋⷦS͛ S͛CͨOͦRͬEͤDͩ";
let totalMarks="* ᴛⷮOͦᴛⷮAͣL MⷨAͣRͬᴋⷦS͛";
let sumOf="  "+marksScored+"    "+totalMarks;
console.log(sumOf);
let engMarks ="𝑬𝑵𝑮𝑳𝑰𝑺𝑯 =        𝟳𝟴 |     ";
let engTotal=(100);
console.log(engMarks+engTotal);
let mathMarks="𝙈𝘼𝙏𝙃𝙀𝙈𝘼𝙏𝙄𝘾𝙎 =    𝟲𝟮 |     ";
let mathTotal=(100);
console.log(mathMarks+mathTotal);
let scienceMarks="𝙎𝘾𝙄𝙀𝙉𝘾𝙀 =        𝟲𝟲 |     ";
let sciTotal=(100);
console.log(scienceMarks+sciTotal);
let end="==================================";
console.log(end);

